[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/abbainovator"
  to = "/templates/abbainovator/index.html"
  status = 200

[[redirects]]
  from = "/alumsist"
  to = "/templates/alumsist/index.html"
  status = 200

[[redirects]]
  from = "/austav"
  to = "/templates/austav/index.html"
  status = 200

[[redirects]]
  from = "/avrekon"
  to = "/templates/avrekon/index.html"
  status = 200

[[redirects]]
  from = "/bomif"
  to = "/templates/bomif/index.html"
  status = 200

[[redirects]]
  from = "/kmdstav"
  to = "/templates/kmdstav/index.html"
  status = 200

[[redirects]]
  from = "/betcon"
  to = "/templates/betcon/index.html"
  status = 200

[[redirects]]
  from = "/dmbauteam"
  to = "/templates/dmbauteam/index.html"
  status = 200

[[redirects]]
  from = "/agim"
  to = "/templates/agim/index.html"
  status = 200

[[redirects]]
  from = "/alurenostav"
  to = "/templates/alurenostav/index.html"
  status = 200

[[redirects]]
  from = "/bosolutions"
  to = "/templates/bosolutions/index.html"
  status = 200

[[redirects]]
  from = "/bsltrading"
  to = "/templates/bsltrading/index.html"
  status = 200

[[redirects]]
  from = "/darton"
  to = "/templates/darton/index.html"
  status = 200

[[redirects]]
  from = "/dobritesari"
  to = "/templates/dobritesari/index.html"
  status = 200

[[redirects]]
  from = "/dzatko-junior"
  to = "/templates/dzatko-junior/index.html"
  status = 200

[[redirects]]
  from = "/efektivnestavby"
  to = "/templates/efektivnestavby/index.html"
  status = 200

[[redirects]]
  from = "/ellio"
  to = "/templates/ellio/index.html"
  status = 200

[[redirects]]
  from = "/ebendomy"
  to = "/templates/ebendomy/index.html"
  status = 200

[[redirects]]
  from = "/hirver"
  to = "/templates/hirver/index.html"
  status = 200

[[redirects]]
  from = "/hnlstavby"
  to = "/templates/hnlstavby/index.html"
  status = 200

[[redirects]]
  from = "/hurtstav"
  to = "/templates/hurtstav/index.html"
  status = 200

[[redirects]]
  from = "/hydrotunel"
  to = "/templates/hydrotunel/index.html"
  status = 200

[[redirects]]
  from = "/inrestsro"
  to = "/templates/inrestsro/index.html"
  status = 200

[[redirects]]
  from = "/kosap"
  to = "/templates/kosap/index.html"
  status = 200

[[redirects]]
  from = "/kostelansky"
  to = "/templates/kostelansky/index.html"
  status = 200

[[redirects]]
  from = "/kronostav"
  to = "/templates/kronostav/index.html"
  status = 200

[[redirects]]
  from = "/la-ma"
  to = "/templates/la-ma/index.html"
  status = 200

[[redirects]]
  from = "/miroslavholecvykopoveprace"
  to = "/templates/miroslavholecvykopoveprace/index.html"
  status = 200

[[redirects]]
  from = "/mmsadrokartony"
  to = "/templates/mmsadrokartony/index.html"
  status = 200

[[redirects]]
  from = "/modularnastavba"
  to = "/templates/modularnastavba/index.html"
  status = 200

[[redirects]]
  from = "/montter"
  to = "/templates/montter/index.html"
  status = 200

[[redirects]]
  from = "/poterymm"
  to = "/templates/poterymm/index.html"
  status = 200

[[redirects]]
  from = "/pramo"
  to = "/templates/pramo/index.html"
  status = 200

[[redirects]]
  from = "/premona-nitra"
  to = "/templates/premona-nitra/index.html"
  status = 200

[[redirects]]
  from = "/pkprojekt"
  to = "/templates/pkprojekt/index.html"
  status = 200

[[redirects]]
  from = "/purdom"
  to = "/templates/purdom/index.html"
  status = 200

[[redirects]]
  from = "/redosi_group"
  to = "/templates/redosi_group/index.html"
  status = 200

[[redirects]]
  from = "/reinter"
  to = "/templates/reinter/index.html"
  status = 200

[[redirects]]
  from = "/revast"
  to = "/templates/revast/index.html"
  status = 200

[[redirects]]
  from = "/soki"
  to = "/templates/soki/index.html"
  status = 200

[[redirects]]
  from = "/soultrade"
  to = "/templates/soultrade/index.html"
  status = 200

[[redirects]]
  from = "/sochabau"
  to = "/templates/sochabau/index.html"
  status = 200

[[redirects]]
  from = "/tostav"
  to = "/templates/tostav/index.html"
  status = 200

[[redirects]]
  from = "/stamaxplus"
  to = "/templates/stamaxplus/index.html"
  status = 200

[[redirects]]
  from = "/starbuilding"
  to = "/templates/starbuilding/index.html"
  status = 200

[[redirects]]
  from = "/stavba-domu-na-kluc"
  to = "/templates/stavba-domu-na-kluc/index.html"
  status = 200

[[redirects]]
  from = "/stavferka"
  to = "/templates/stavferka/index.html"
  status = 200

[[redirects]]
  from = "/vo-vyske"
  to = "/templates/vo-vyske/index.html"
  status = 200

[[redirects]]
  from = "/windoo"
  to = "/templates/windoo/index.html"
  status = 200

[[redirects]]
  from = "/stavmixv-naj"
  to = "/templates/stavmixv-naj/index.html"
  status = 200

[[redirects]]
  from = "/ekodat"
  to = "/templates/ekodat/index.html"
  status = 200

[[redirects]]
  from = "/zamkovadlazbamartin"
  to = "/templates/zamkovadlazbamartin/index.html"
  status = 200

[[redirects]]
  from = "/espron"
  to = "/templates/espron/index.html"
  status = 200

[[redirects]]
  from = "/dclpartners"
  to = "/templates/dclpartners/index.html"
  status = 200

[[redirects]]
  from = "/roneprojekt"
  to = "/templates/roneprojekt/index.html"
  status = 200

[[redirects]]
  from = "/soldout"
  to = "/templates/soldout/index.html"
  status = 200

[[redirects]]
  from = "/mkem"
  to = "/templates/mkem/index.html"
  status = 200

[[redirects]]
  from = "/odes"
  to = "/templates/odes/index.html"
  status = 200

[[redirects]]
  from = "/bma-dk"
  to = "/templates/bma-dk/index.html"
  status = 200

[[redirects]]
  from = "/likvidaciaazbestu"
  to = "/templates/likvidaciaazbestu/index.html"
  status = 200

[[redirects]]
  from = "/riljak"
  to = "/templates/riljak/index.html"
  status = 200

[[redirects]]
  from = "/klimaelektro"
  to = "/templates/klimaelektro/index.html"
  status = 200

[[redirects]]
  from = "/jmstrechy7"
  to = "/templates/jmstrechy7/index.html"
  status = 200

[[redirects]]
  from = "/pvwin"
  to = "/templates/pvwin/index.html"
  status = 200

[[redirects]]
  from = "/pemtrade"
  to = "/templates/pemtrade/index.html"
  status = 200

[[redirects]]
  from = "/ekoploty"
  to = "/templates/ekoploty/index.html"
  status = 200

[[redirects]]
  from = "/ivpstavby"
  to = "/templates/ivpstavby/index.html"
  status = 200

[[redirects]]
  from = "/tisplus"
  to = "/templates/tisplus/index.html"
  status = 200

[[redirects]]
  from = "/az-real"
  to = "/templates/az-real/index.html"
  status = 200

[[redirects]]
  from = "/stavbyjaniss"
  to = "/templates/stavbyjaniss/index.html"
  status = 200

[[redirects]]
  from = "/timbed"
  to = "/templates/timbed/index.html"
  status = 200

[[redirects]]
  from = "/brunelstav"
  to = "/templates/brunelstav/index.html"
  status = 200

[[redirects]]
  from = "/jakubasek"
  to = "/templates/jakubasek/index.html"
  status = 200

[[redirects]]
  from = "/rambet"
  to = "/templates/rambet/index.html"
  status = 200

[[redirects]]
  from = "/zembau"
  to = "/templates/zembau/index.html"
  status = 200

[[redirects]]
  from = "/sperostav"
  to = "/templates/sperostav/index.html"
  status = 200

[[redirects]]
  from = "/pestastav"
  to = "/templates/pestastav/index.html"
  status = 200

[[redirects]]
  from = "/gekotech"
  to = "/templates/gekotech/index.html"
  status = 200

[[redirects]]
  from = "/bautop"
  to = "/templates/bautop/index.html"
  status = 200

[[redirects]]
  from = "/bouwgroup"
  to = "/templates/bouwgroup/index.html"
  status = 200

[[redirects]]
  from = "/matfiakdistribution"
  to = "/templates/matfiakdistribution/index.html"
  status = 200

[[redirects]]
  from = "/armakov"
  to = "/templates/armakov/index.html"
  status = 200

[[redirects]]
  from = "/petruslm"
  to = "/templates/petruslm/index.html"
  status = 200

[[redirects]]
  from = "/podlahovecentrumbj"
  to = "/templates/podlahovecentrumbj/index.html"
  status = 200

[[redirects]]
  from = "/rbltrade"
  to = "/templates/rbltrade/index.html"
  status = 200

[[redirects]]
  from = "/riaplast"
  to = "/templates/riaplast/index.html"
  status = 200

[[redirects]]
  from = "/granila"
  to = "/templates/granila/index.html"
  status = 200

[[redirects]]
  from = "/pavstav"
  to = "/templates/pavstav/index.html"
  status = 200

[[redirects]]
  from = "/pvbstav"
  to = "/templates/pvbstav/index.html"
  status = 200

[[redirects]]
  from = "/vialle"
  to = "/templates/vialle/index.html"
  status = 200

[[redirects]]
  from = "/md-project"
  to = "/templates/md-project/index.html"
  status = 200

[[redirects]]
  from = "/izobetonlevice"
  to = "/templates/izobetonlevice/index.html"
  status = 200

[[redirects]]
  from = "/bomati"
  to = "/templates/bomati/index.html"
  status = 200
